#!/usr/bin/env python
"""--------------------------------------------------------------------
Copyright (c) 2017, Kinova Robotics inc.

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

	* Redistributions of source code must retain the above copyright notice,
	  this list of conditions and the following disclaimer.
	* Redistributions in binary form must reproduce the above copyright notice,
	  this list of conditions and the following disclaimer in the documentation
	  and/or other materials provided with the distribution.
	* Neither the name of the copyright holder nor the names of its contributors
	  may be used to endorse or promote products derived from this software
	  without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR 
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
	
 \file   init_robot

 \brief  Initialize robot 

 \Platform: Ubuntu 16.04 LTS / ROS Kinetic
--------------------------------------------------------------------"""
import sys, rospy, numpy
from std_msgs.msg import Bool
from moveit_python import MoveGroupInterface
from moveit_msgs.msg import MoveItErrorCodes
from movo_action_clients.gripper_action_client import GripperActionClient
import moveit_commander

from geometry_msgs.msg import PoseStamped, Pose
from moveit_commander import RobotCommander, MoveGroupCommander, PlanningSceneInterface
from math import radians

if __name__ == "__main__":
	rospy.init_node('init_robot')
	
	move_group = MoveGroupInterface("upper_body","base_link")
	move_group.setPlannerId("RRTConnectkConfigDefault")
	lgripper = GripperActionClient('left')
	rgripper = GripperActionClient('right')
	dof = rospy.get_param('~jaco_dof')
	initialized = rospy.get_param('~initialized')

	if initialized:
		rospy.set_param('~initialized', False)

	rgripper_type = rospy.get_param('~gripper_right', 'kg3')
	lgripper_type = rospy.get_param('~gripper_left', 'kg3')

	if ("6dof" == dof):
		upper_body_joints = ["right_elbow_joint",
							"right_shoulder_lift_joint",
							"right_shoulder_pan_joint",
							"right_wrist_1_joint",
							"right_wrist_2_joint",
							"right_wrist_3_joint",
							"left_elbow_joint",
							"left_shoulder_lift_joint",
							"left_shoulder_pan_joint",
							"left_wrist_1_joint",
							"left_wrist_2_joint",
							"left_wrist_3_joint",
							"linear_joint",
							"pan_joint",
							"tilt_joint"]
		homed = [-2.135,-0.227,-1.478,-2.083,1.445,1.321,2.135,0.227,1.478,2.083,-1.445,-1.321,0.35,0.0,0.0]
		tucked = [-2.8,-1.48,-1.48,0,0,1.571, 2.8,1.48,1.48,0,0,-1.571,0.0371,0.0,0.0]
		if (rgripper_type == 'rq85'):
			tucked[5] -= 1.571
		if (lgripper_type == 'rq85'):
			tucked[11] += 1.571


	elif ("7dof" == dof):
		upper_body_joints = ["right_shoulder_pan_joint",
							"right_shoulder_lift_joint",
							"right_arm_half_joint",
							"right_elbow_joint",
							"right_wrist_spherical_1_joint",
							"right_wrist_spherical_2_joint",
							"right_wrist_3_joint",
							"left_shoulder_pan_joint",
							"left_shoulder_lift_joint",
							"left_arm_half_joint",
							"left_elbow_joint",
							"left_wrist_spherical_1_joint",
							"left_wrist_spherical_2_joint",
							"left_wrist_3_joint",
							"linear_joint",
							"pan_joint",
							"tilt_joint"]

		homed = [-1.5,-0.2,-0.15,-2.0,2.0,-1.24,-1.1, 1.5,0.2,0.15,2.0,-2.0,1.24,1.1,0.35,0,0]
		tucked = [-1.6,-1.4,0.4,-2.7,0.0,0.5,-1.7, 1.6,1.4,-0.4,2.7,0.0,-0.5, 1.7, 0.04, 0, 0]
		if (rgripper_type == 'rq85'):
			tucked[6] -= numpy.radians(60.0)
		if (lgripper_type == 'rq85'):
			tucked[13] += numpy.radians(60.0)
	else:
		rospy.logerr("DoF needs to be set 6 or 7, aborting process")
		exit()

	# This is a hardware so need to adjust gripper parameters
	gripper_closed = 0.01
	gripper_open = 0.165

	lgripper.command(gripper_closed)
	rgripper.command(gripper_closed)

	success=False
	while not rospy.is_shutdown() and not success:
		
		result = move_group.moveToJointPosition(upper_body_joints, homed, 0.05)
		if result.error_code.val == MoveItErrorCodes.SUCCESS:
			success = True
		else:
			rospy.logerr("moveToJointPosition failed (%d)" %result.error_code.val)

	rospy.sleep(5)
	success=False
	while not rospy.is_shutdown() and not success:
		result = move_group.moveToJointPosition(upper_body_joints, tucked, 0.05)
		if result.error_code.val == MoveItErrorCodes.SUCCESS:
			success = True

	lgripper.command(gripper_closed)
	rgripper.command(gripper_closed)

	#############################  Attach Camera_Zhiyang  ##################################

	# Define Scene Object
	scene = PlanningSceneInterface()
    rospy.sleep(1)

	# Initialize arm group from moveit group to control manipulator
    rarm = MoveGroupCommander('right_arm')
	larm = MoveGroupCommander('left_arm')

	# Get end effector link name
	r_end_effector_link = rarm.get_end_effector_link()
	l_end_effector_link = larm.get_end_effector_link()

	# Set tolerance of position(m) and orentation(rad)
	rarm.set_goal_position_tolerance(0.01)
	rarm.set_goal_orientation_tolerance(0.05)
	larm.set_goal_position_tolerance(0.01)
	larm.set_goal_orientation_tolerance(0.05) 

	# Set size of camera
	tool_size = [0.15, 0.15, 0.06]

	# Set orentation and position of tool
	p1 = PoseStamped()
	p1.header.frame_id = r_end_effector_link
	
	p1.pose.position.x = -0.07
	p1.pose.position.y = 0.0
	p1.pose.position.z = 0.08
	p1.pose.orientation.x = 0
	p1.pose.orientation.y = 0
	p1.pose.orientation.z = 0
	p1.pose.orientation.w = 1

	p2 = PoseStamped()
	p2.header.frame_id = l_end_effector_link
	
	p2.pose.position.x = -0.07
	p2.pose.position.y = 0.0
	p2.pose.position.z = 0.08
	p2.pose.orientation.x = 0
	p2.pose.orientation.y = 0
	p2.pose.orientation.z = 0
	p2.pose.orientation.w = 1

	# Make tool attact to end effector
	scene.attach_box(r_end_effector_link, 'Camera1', p1, tool_size)
	scene.attach_box(l_end_effector_link, 'Camera2', p2, tool_size)

	# Update current state (position and orentation)
	rarm.set_start_state_to_current_state()
	larm.set_start_state_to_current_state()
	########################################################################################

	rospy.sleep(5)
	rospy.set_param('~initialized', True)
