# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from movo_arc_lib/dual_task_move_safe_relateGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class dual_task_move_safe_relateGoal(genpy.Message):
  _md5sum = "261ae4ae306d100fb103ad49ad1cca09"
  _type = "movo_arc_lib/dual_task_move_safe_relateGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
float32[3] pos_r
float32[3] pos_l
float32[6] r_max_force
float32[6] l_max_force
float32 time
"""
  __slots__ = ['pos_r','pos_l','r_max_force','l_max_force','time']
  _slot_types = ['float32[3]','float32[3]','float32[6]','float32[6]','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pos_r,pos_l,r_max_force,l_max_force,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(dual_task_move_safe_relateGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.pos_r is None:
        self.pos_r = [0.] * 3
      if self.pos_l is None:
        self.pos_l = [0.] * 3
      if self.r_max_force is None:
        self.r_max_force = [0.] * 6
      if self.l_max_force is None:
        self.l_max_force = [0.] * 6
      if self.time is None:
        self.time = 0.
    else:
      self.pos_r = [0.] * 3
      self.pos_l = [0.] * 3
      self.r_max_force = [0.] * 6
      self.l_max_force = [0.] * 6
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_3f().pack(*self.pos_r))
      buff.write(_get_struct_3f().pack(*self.pos_l))
      buff.write(_get_struct_6f().pack(*self.r_max_force))
      buff.write(_get_struct_6f().pack(*self.l_max_force))
      _x = self.time
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 12
      self.pos_r = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.pos_l = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 24
      self.r_max_force = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 24
      self.l_max_force = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (self.time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.pos_r.tostring())
      buff.write(self.pos_l.tostring())
      buff.write(self.r_max_force.tostring())
      buff.write(self.l_max_force.tostring())
      _x = self.time
      buff.write(_get_struct_f().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 12
      self.pos_r = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.pos_l = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 24
      self.r_max_force = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=6)
      start = end
      end += 24
      self.l_max_force = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=6)
      start = end
      end += 4
      (self.time,) = _get_struct_f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
